### ISSUE TITLE
Message Browser out of date

### ISSUE THREAD

**Issue by airs747** [mykle1/MMM-EARTH-Live#3]
It works, but the video shows a message "Your browser is out of date" over the image of the earth...
Any ideas?

**Comment by mykle1** [comment]
Yes, this just started with both this module and MMM-ISS-Live. It's coming from the source so I'm going to have to figure out how to handle it. 

However, if you have the ability to click or touch you can simply "x" out the message and the module performs as expected. Even after several restarts that message does not reappear

**Comment by airs747** [comment]
OK cool, thanks, hadn't thought of that, sorry
NB: The live broadcast/experiment stopped August 22, maybe good to mention
that

https://eol.jsc.nasa.gov/ESRS/HDEV/
High Definition Earth-Viewing System (HDEV)
Currently, a continuous loop of previously recorded HDEV video is displayed
in the window below. After HDEV stopped sending any data on July 18, 2019,
it was declared, on August 22, 2019, to have reached its end of life.
Future methods for showing live steaming video of the Earth from the ISS
are being assessed. Thank You to all who shared in experiencing and using
the HDEV views of Earth from the ISS to make HDEV so much more than a
Technology Demonstration Payload!

The High Definition Earth Viewing (HDEV) experiment mounted on the ISS
External Payload Facility of the European Space Agency’s Columbus module
was activated April 30, 2014 and after 5 years and 79 days was viewed by
more than 318 million viewers across the globe on USTREAM alone.

To learn more about the HDEV experiment, visit here.

best,
arjen

**Comment by mykle1** [comment]
Updated readme
