### ISSUE TITLE
brouwser error

### ISSUE THREAD

**Issue by Dylantje** [mykle1/MMM-EARTH-Live#4]
hi thanks for the great work!!
Question i get a error browser need a update, only i use the lastes version of pi software

**Comment by mykle1** [comment]
Yes, I'm aware of this behavior. I think it has to do with electron (the browser that MM uses). You can try 2 things. If you have a mouse connected to your mirror you can close out the error message and the video will clear. You can also try pressing "CONTROL R" while the mirror is running. This will reload the mirror. The error message should be gone at this point. Sorry about the trouble.
