### ISSUE TITLE
502 (Bad Gateway) eventtracking-log.services.video.ibm.com/:1

### ISSUE THREAD

**Issue by ghost** [mykle1/MMM-EARTH-Live#6]
Failed to load resource: the server responded with a status of 502 (Bad Gateway) eventtracking-log.services.video.ibm.com/:1

**Comment by mykle1** [comment]
I have not seen this behavior

**Comment by ghost** [comment]
reporting you for abuse, you dont know what you're doing and all you seem to do is insult people and delete comments, you're a trash programmer also that cant fix solutions or even find his own problems, have fun with your old self, ive moved onto react and built my own apps and copied yours because yours dont work and are generally garbage (because you probably just copied them lol), peace

**Comment by ghost** [comment]
> I have not seen this behavior

thats because you have no idea what youre doing and cant even find your own issues in your own program, you should listen to your son, he already seems smarter than you, you might be too old to have the patience for this

**Comment by ghost** [comment]
oh dont bother replying btw, unsubscribed to your notifications because you dont know how to fix anything and probably just copied all this code anyway, enjoy being mad at things for pretty much no reason, bye lol
