### ISSUE TITLE
Module does not start video

### ISSUE THREAD

**Issue by Egorarchitec** [mykle1/MMM-EARTH-Live#7]
Despite the line that was already been in an electron.js  the feed won't start playing. I just see an initial frame of the stream with play bottom in the middle. What could be a problem?

**Comment by Emilienhrlt** [comment]
Hello,

I have the same issue. I have to click to start playing.
The added line was already been in the electron.js

**Comment by mykle1** [comment]
I'm looking into it. When MM moved to a newer version of Electron it broke the fix. In the meantime, if you have a mouse connected you can click the play button, obviously

**Comment by mykle1** [comment]
@Emilienhrlt

Have you tried loading the module  and leaving it to run for a few minutes? I just loaded it and left MM running. Within a few minutes the video started without any user interaction. Same thing for MMM-EARTH-Live. Just a thought . . .

**Comment by krnlerror992** [comment]
Hi,

I have the same issue. I have to click to start playing.
The added line was already been in the electron.js.
When i start mm in dev mode i get this: 

Access to XMLHttpRequest at 'http://eventtracking-log.services.video.ibm.com/eventtracking.web.player/' from origin 'http://www.ustream.tv'  '17074538?html5ui?autoplay=1:1'http://www.ustream.tv' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
POST http://eventtracking-log.services.video.ibm.com/eventtracking.web.player/ net::ERR_FAILED
